services:
  app:
    build:
      context: ..
      dockerfile: infra/service.Dockerfile
      target: debug
    container_name: app-be
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-net
    env_file:
      - server.env
    environment:
      MONGO_URI: "mongodb://${MONGO_APP_USERNAME}:${MONGO_APP_PASSWORD}@mongodb:27017/${MONGO_DATABASE}?authSource=${MONGO_DATABASE}"
      MONGO_DATABASE: "${MONGO_DATABASE}"
    volumes:
      - ../src:/app/src
    restart: always
    ports:
      - "8080:8080"
      - "2345:2345"
    security_opt:
      - "seccomp:unconfined"
  mongodb:
    build:
      context: .
      dockerfile: mongodb.Dockerfile
      args:
        MONGO_VERSION: "${MONGO_VERSION:-8.0.4}"
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      GLIBC_TUNABLES: glibc.pthread.rseq=0
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}

      # Variables used by mongo-init.js
      MONGO_APP_USERNAME: ${MONGO_APP_USERNAME}
      MONGO_APP_PASSWORD: ${MONGO_APP_PASSWORD}

    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --quiet --username \"$${MONGO_INITDB_ROOT_USERNAME}\" --password \"$${MONGO_INITDB_ROOT_PASSWORD}\" --authenticationDatabase admin --eval 'db.runCommand({ ping: 1 }).ok' | grep 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

    networks:
      - app-net

networks:
  app-net:
    driver: bridge
volumes:
  images_volume:
  mongodb_data:
  mongodb_config:
